### ISSUE TITLE
paffy  tile  error 

### ISSUE THREAD

**Issue by zhangyixing3** [HFzzzzzzz/ACMGA#3]
Hello, I've encountered an issue with Paffy Tile; it's showing inconsistent lengths for chromosome Chr1. After checking the anchorwave_chain.paf file, I noticed that the query sequences for Chr1 have different lengths.
![image](https://github.com/HFzzzzzzz/ACMGA/assets/91043462/c870cb42-0d2a-4ef3-8b40-106d5ba55567)
![image](https://github.com/HFzzzzzzz/ACMGA/assets/91043462/7b5859e4-49cf-4c83-b213-392bcd6d370b)

Note :   I am using version 1.2.3 of the anchorwave
How to solve this problem?

**Comment by zhangyixing3** [comment]
https://github.com/ComparativeGenomicsToolkit/paffy/blob/2430fb53d48e9791cdb36cbdfe3c8895eecb79b3/impl/paf.c#L584
line 589  seq_count_array->length = paf->query_length; 
line 594  assert(seq_count_array->length == paf->query_length);
It's possible that there's an error on line 594.

**Comment by HFzzzzzzz** [comment]
> https://github.com/ComparativeGenomicsToolkit/paffy/blob/2430fb53d48e9791cdb36cbdfe3c8895eecb79b3/impl/paf.c#L584 line 589 seq_count_array->length = paf->query_length; line 594 assert(seq_count_array->length == paf->query_length); It's possible that there's an error on line 594.

What data did you use? Please use AnchorWave version 1.2.1, or AnchorWave version 1.2.2. Because AnchorWave fixed the negative chain comparison problem in version 1.2.3, there is no need to replace part of the content in replace_ref_que.py to correct the negative chain alignment problem. If you want to use AnchorWave1.2.3, please check whether the maf file generated by AnchorWave is correct, and comment out the code on line 23 and later of replace_ref_que.py, which may solve this problem.

**Comment by zhangyixing3** [comment]
The latest  anchorwave and  Chromosome id should  beginning with "chr" or "Chr" https://github.com/HFzzzzzzz/ACMGA/pull/4
